site_name: PhotonLibPy Docs
theme:
  name: material
  favicon: docs/favicon.ico  # If you want a favicon
  logo: logo.svg        # Optional logo
  palette:
    primary: custom

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - "."
  - gen-files:
      scripts:
        - gen_api_docs.py
  - literate-nav
  - section-index
  # To exclude files, add them under glob using their
  # path from photonlibpy prepended by reference/
  # Additionally, change the extension from .py to .md
  - exclude:
      glob:
        - "reference/packet.md"

nav:
  - Home: index.md
  - Reference: reference/SUMMARY.md

extra_css:
  - stylesheets/extra.css
