site_name: PhotonLibPy Docs
theme:
  name: material
  favicon: images/favicon.ico  # If you want a favicon
  logo: images/logo.png        # Optional logo

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          setup_commands:
            - import sys; sys.path.append(".")
  - gen-files:
      scripts:
        - gen_api_docs.py
  - literate-nav
  - section-index

nav:
  - Home: index.md
  - Reference: reference/SUMMARY.md

