site_name: PhotonLibPy Docs
theme:
  name: material
  favicon: docs/favicon.ico  # If you want a favicon
  logo: docs/logo.png        # Optional logo

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: 
            - "."
  - gen-files:
      scripts:
        - gen_api_docs.py
  - literate-nav
  - section-index

nav:
  - Home: index.md
  - Reference: reference/SUMMARY.md

